language: node_js
node_js:
- "stable"

install:
- npm install -g truffle
- npm install -g ganache-cli
- npm install -g coveralls
- npm install

script:
- npm run test

after_success:
- export CURRENT_VERSION=$(node -p "require('./package.json').version")
- export LATEST=$(npm view $(node -p "require('./package.json').name") dist-tags.latest)
- export NEXT=$(npm view $(node -p "require('./package.json').name") dist-tags.next)
- npm run coverage && cat coverage/lcov.info | coveralls

before_deploy:
- if [ "$LATEST" != "$CURRENT_VERSION" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  echo "on master branch";
  export TRAVIS_TAG=v$CURRENT_VERSION;
  fi;
- if [ "$NEXT" != "$CURRENT_VERSION" ] && [ "$TRAVIS_BRANCH" = "develop" ]; then
  echo "on develop branch";
  export TRAVIS_TAG=v$CURRENT_VERSION-next;
  fi;

deploy:
- provider: npm
  email: email@wanseob.com
  api_key:
    secure: FmAB3Bee6zJa6s6hAnUELCRopRkD9M0uV4YL4W54N1GBcwUDPzviup67+e7XZVI4JJXNviD/t+5RlDCd0OdV4JnE6h70UBzeQTVu+lzauSRBflJfyO3FZ8szJwmYxldTMaYHEG07UqL6anc4Qn1GI16wppzG+sVHl7siGSgCkl5mxTclzW4DYjnm5KpBiWf3qzx3usK/5UrZMt+s/pTOkZ+BLAh30UcAhR07en00Ky/ouFj2R4zjJK7ZMrElVxx9SpI41ds/RGUFClL6e1Yc6b8pRtbVu9t7jMBpfck2c81s9GS1alD6JsWASARx4NQvw94zGMhwGYUyYEviB0jinvkJpKfTmcWUF0gASWkUPZvzybbSul39To0grUj5pHwUihhsSm68kaRmkGh5oCthMwF8mJ23L4T8fK5IHRgFizffmU3up18poRZn20gpp71WleaRDEg73AC8jXWWWhcAmy70L9iIaQ1+mVi9vJY+ykGzJlBv4tfZ1fTjQLalayU/NeIv5sUZ31zmRoUA2JUgOuAvlpKWD2tZW4ch0k91NNBjuSmHJebzSp6IQ4TS0lMjJ6NvE+OVpbselAwsjlslN6/opbDzhcIYow7/Lr4dOT0bA9N68ssBoguUKkoO5RwavE4QoWoO0AAgRYcvuqiKM9+PFLA+SiLiBv6RX+8DFZ4=
  tag: next
  on:
    condition: $NEXT != $CURRENT_VERSION
    tags: true
    repo: commitground/solidity-partial-tree
  on:
    branch: develop
    repo: commitground/solidity-partial-tree
- provider: npm
  email: email@wanseob.com
  api_key:
    secure: FmAB3Bee6zJa6s6hAnUELCRopRkD9M0uV4YL4W54N1GBcwUDPzviup67+e7XZVI4JJXNviD/t+5RlDCd0OdV4JnE6h70UBzeQTVu+lzauSRBflJfyO3FZ8szJwmYxldTMaYHEG07UqL6anc4Qn1GI16wppzG+sVHl7siGSgCkl5mxTclzW4DYjnm5KpBiWf3qzx3usK/5UrZMt+s/pTOkZ+BLAh30UcAhR07en00Ky/ouFj2R4zjJK7ZMrElVxx9SpI41ds/RGUFClL6e1Yc6b8pRtbVu9t7jMBpfck2c81s9GS1alD6JsWASARx4NQvw94zGMhwGYUyYEviB0jinvkJpKfTmcWUF0gASWkUPZvzybbSul39To0grUj5pHwUihhsSm68kaRmkGh5oCthMwF8mJ23L4T8fK5IHRgFizffmU3up18poRZn20gpp71WleaRDEg73AC8jXWWWhcAmy70L9iIaQ1+mVi9vJY+ykGzJlBv4tfZ1fTjQLalayU/NeIv5sUZ31zmRoUA2JUgOuAvlpKWD2tZW4ch0k91NNBjuSmHJebzSp6IQ4TS0lMjJ6NvE+OVpbselAwsjlslN6/opbDzhcIYow7/Lr4dOT0bA9N68ssBoguUKkoO5RwavE4QoWoO0AAgRYcvuqiKM9+PFLA+SiLiBv6RX+8DFZ4=
  tag: latest
  on:
    condition: $LATEST != $CURRENT_VERSION
    tags: true
    repo: commitground/solidity-partial-tree
  on:
    branch: master
    repo: commitground/solidity-partial-tree

- provider: releases
  api_key:
    secure: V5eGBJvkmXzwZ0op21QgUupDnRAmSVUpAX7mtuHn+vJqNlv+A5aYP+vpngxDktHj/yzqxI4zjFoifyhZPpKMfHNqg9XG6XY8wyoD2MmQdqULFa7jrIqW/HcdTBsSJYSWvC2K5/B0Agd9zII7mKkK2Qdk4IMB7mIZ2MXLhZOyik288YY+h3tNGDq+A7oOmj3/VyxKtLq6YRQLGvB7KdJw2UFhuC0WUOsUwX7dVytwphB1V4lC5c4hci9tyeqKP55bf5R5B5m4cGhBPSm647Baz41MO9JA01sjQSi84ho6k/tOmR3zbeFHNpMfZc4HZfP52VNKkClH0SGSqWQYjJeXwcs3xFG6TE+lDPcPAE7a6983LIYm2W97aaq1RiYSshbc3+6bYUjURxJNzjHVmDRI0OVqLc0sBVcvK4Z7lhp0T4sgGAdn2Up1RAmHySHSJq/It0C7BOzHAggpY5wDTzR0UZOtGajPF7bRmiAbeFHC6TCqBPq4Ao88+HoyRJzya0OrL+vmLUpdK7UXgCn2z/043oEjp+3GP7AllshZxeqmuzy/gsrjcERPtn8LvnffYO0dBA40e0AyuZbu+ArMU+xDKnLUITb8Ue7rXYEVs7crVHJVSYegXghCvVeD5WAjlOaKZ8kzKKI2u6r26FdIptUMSThBfjPQuqqZVXA+dxc22g0=
  on:
    tags: true
    repo: commitground/solidity-partial-tree
    branch: master
