language: node_js
node_js:
- "stable"

install:
- npm install -g truffle
- npm install -g ganache-cli
- npm install -g coveralls
- npm install

script:
- npm run test

after_success:
- export CURRENT_VERSION=$(node -p "require('./package.json').version")
- export LATEST=$(npm view $(node -p "require('./package.json').name") dist-tags.latest)
- export NEXT=$(npm view $(node -p "require('./package.json').name") dist-tags.next)
- npm run coverage && cat coverage/lcov.info | coveralls

before_deploy:
- if [ "$LATEST" != "$CURRENT_VERSION" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  echo "on master branch";
  export TRAVIS_TAG=v$CURRENT_VERSION;
  fi;
- if [ "$NEXT" != "$CURRENT_VERSION" ] && [ "$TRAVIS_BRANCH" = "develop" ]; then
  echo "on develop branch";
  export TRAVIS_TAG=v$CURRENT_VERSION-next;
  fi;

deploy:
- provider: npm
  email: admin.npm@commitground.io
  api_key:
    secure: qi+8tuTrqap0iUIQxwyzVu3+nhW3RYA2u00lg88vvlVVxngeDzW6E96SCZfo7FMnCGJoxGoa50RK/XKyfBKSw/fSTV8TtEfGWCoIsvfYRk1h5/z/rA4lJCoxZQ6s22ne12tkCzU8++cyIu2ybb1tiZoBUWMwmnPrFYZBEazj3sm7hYKJCbwpMiN6j79YdZdG13E1/W2lQxlttBJX0DnahBsjSmNpW8lKUhpZ0xTxG62pv0ET9gv968sJLGP5nU4G66nJpALZHrVdYDybDPUZBvkNpDi7uwfXN+a9oJbBT1iAW98L5ManyoV8A3Ybwnwgie7qV6yMYHsWKuHYSQxTX6cK4I8np2dpxLL3gPQOkubZxy4oQUn6Ay3ziAw3PSOKlLd3NPRmF6w4amw8H6yfwrFR61sguPFvRsyO/PO97LTNepHvaNXJJAaPnsalhyKQ+4jf+Cc7UTuvT+2GgxByoVoqyAL16DtBkYae37oCosHJRKLSl4m1i56z3Gciea7dljcEpByEDiB5MH9o2gt9VA6BlFvOx6jhXv8J1EWC8FNB+eGbI/5OBuyaWFe39ADq6j1pRz+iHDBOe78gP94TycSCd4HdTrmshshHNXQdO/+H9vNzp67C6SVMFqlqZiIZIi4LhYCziK74st/XM1Zi3qqEh+pNtIQbH6vvNrN3FDQ=
  tag: next
  on:
    condition: $NEXT != $CURRENT_VERSION
    branch: develop
    repo: commitground/solidity-patricia-tree
- provider: npm
  email: admin.npm@commitground.io
  api_key:
    secure: qi+8tuTrqap0iUIQxwyzVu3+nhW3RYA2u00lg88vvlVVxngeDzW6E96SCZfo7FMnCGJoxGoa50RK/XKyfBKSw/fSTV8TtEfGWCoIsvfYRk1h5/z/rA4lJCoxZQ6s22ne12tkCzU8++cyIu2ybb1tiZoBUWMwmnPrFYZBEazj3sm7hYKJCbwpMiN6j79YdZdG13E1/W2lQxlttBJX0DnahBsjSmNpW8lKUhpZ0xTxG62pv0ET9gv968sJLGP5nU4G66nJpALZHrVdYDybDPUZBvkNpDi7uwfXN+a9oJbBT1iAW98L5ManyoV8A3Ybwnwgie7qV6yMYHsWKuHYSQxTX6cK4I8np2dpxLL3gPQOkubZxy4oQUn6Ay3ziAw3PSOKlLd3NPRmF6w4amw8H6yfwrFR61sguPFvRsyO/PO97LTNepHvaNXJJAaPnsalhyKQ+4jf+Cc7UTuvT+2GgxByoVoqyAL16DtBkYae37oCosHJRKLSl4m1i56z3Gciea7dljcEpByEDiB5MH9o2gt9VA6BlFvOx6jhXv8J1EWC8FNB+eGbI/5OBuyaWFe39ADq6j1pRz+iHDBOe78gP94TycSCd4HdTrmshshHNXQdO/+H9vNzp67C6SVMFqlqZiIZIi4LhYCziK74st/XM1Zi3qqEh+pNtIQbH6vvNrN3FDQ=
  tag: latest
  on:
    condition: $LATEST != $CURRENT_VERSION
    branch: master
    repo: commitground/solidity-patricia-tree
- provider: releases
  api_key:
    secure: meyzpOOwwLKhWGU0gy0RDXnX0lBFlmIlN3SPADDMMCQ6ewxBpfwW/LsJMpIqyGQ/gZ/TdR/P5ITQn8SOlD/ZHWiPhPQvTYRzIEzRakx4ngms0o9KhphDJywCNk2T/vNMi64SRt7Fcu+6truIR2IHU7qHk9BcGz1xFTzK6b8WueTbVUS295l5pfZZfq1pwQnnY/5JxIMphyi3H5eJL/UmgB1PkPHNW+9YSnE83m7mVAfJGZpsFGDu2eNDXMCxWpgLTG69QaoMKWU3IAj+YJ6lefhy8dXWP78+mJgpyNnjEc25YctpGDa+EKsJ8wZut/fbJhAmPPk4xAk/Uxa1KSM/O73Or630dDAcbJ0AmdFWKwshKBf/ZuAi4YEQawaY4qn3r6hrvPknXCtJN8VCdpcDBv2gE31MdJFZZJf/CrMYmKUiR/6nWAZh1cJjioYLnfnWBRwJ1oFH1szrtRQc1gKcqrh95SKs1R1Z010a9yuso6XbH4NAArKE0elJteLbcLjEDYNeI7B6XZZlvYJsKerKAQxq8wf0KAybI21xtmqumWn2Y2sogUNOXiV86YbRVQ2HSJV2WA1ljZvbd+3r5c8LlB3GAdyKzCknAgo0+3hDWv3JyRyMdtO8IKJBDvV6p1PH/eB0e7txKtacSl5pLkyi28Nj+lx/de0W2rcw23UR7vM=
  on:
    tags: true
    repo: commitground/solidity-patricia-tree
    branch: master
- provider: releases
  prerelease: true
  api_key:
    secure: meyzpOOwwLKhWGU0gy0RDXnX0lBFlmIlN3SPADDMMCQ6ewxBpfwW/LsJMpIqyGQ/gZ/TdR/P5ITQn8SOlD/ZHWiPhPQvTYRzIEzRakx4ngms0o9KhphDJywCNk2T/vNMi64SRt7Fcu+6truIR2IHU7qHk9BcGz1xFTzK6b8WueTbVUS295l5pfZZfq1pwQnnY/5JxIMphyi3H5eJL/UmgB1PkPHNW+9YSnE83m7mVAfJGZpsFGDu2eNDXMCxWpgLTG69QaoMKWU3IAj+YJ6lefhy8dXWP78+mJgpyNnjEc25YctpGDa+EKsJ8wZut/fbJhAmPPk4xAk/Uxa1KSM/O73Or630dDAcbJ0AmdFWKwshKBf/ZuAi4YEQawaY4qn3r6hrvPknXCtJN8VCdpcDBv2gE31MdJFZZJf/CrMYmKUiR/6nWAZh1cJjioYLnfnWBRwJ1oFH1szrtRQc1gKcqrh95SKs1R1Z010a9yuso6XbH4NAArKE0elJteLbcLjEDYNeI7B6XZZlvYJsKerKAQxq8wf0KAybI21xtmqumWn2Y2sogUNOXiV86YbRVQ2HSJV2WA1ljZvbd+3r5c8LlB3GAdyKzCknAgo0+3hDWv3JyRyMdtO8IKJBDvV6p1PH/eB0e7txKtacSl5pLkyi28Nj+lx/de0W2rcw23UR7vM=
  on:
    tags: true
    repo: commitground/solidity-patricia-tree
    branch: develop
